name: helm

on:
  workflow_call:
    inputs:
      samoHelmSourceDir:
        description: 'Helm source directory path'
        default: 'src/main/helm'
        required: false
        type: string
      samoHelmSourceCopy:
        description: 'Samo copy and filter helm source directory'
        default: 'false'
        required: false
        type: string
      packageDir:
        description: 'Package directory'
        default: 'target'
        required: false
        type: string
jobs:
  docker:
    name: build and push
    # runs-on: [ self-hosted, aws ]
    runs-on: ubuntu-latest
    env:
      SAMO_DOCKER_REGISTRY: ghcr.io
      SAMO_DOCKER_RELEASE_REGISTRY: ghcr.io
      SAMO_HELM_SOURCE_DIR: ${{ inputs.samoHelmSourceDir }}
      SAMO_HELM_SOURCE_COPY: ${{ inputs.samoHelmSourceCopy }}
      SAMO_HELM_REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts      
      SAMO_HELM_DIR: target/helm
      SAMO_HELM_CHART_TEMPLATE_LIST: 'version={{ .Version }},appVersion={{ .Version }},name={{ .Name }}'
      SAMO_HELM_VALUES_TEMPLATE_LIST: "app.image.registry=${SAMO_DOCKER_REGISTRY},app.image.tag={{ .Version }},app.image.repository=1000kit/{{ .Name }}"
      SAMO_HELM_PUSH_TYPE: 'harbor'
      SAMO_HELM_VALUES_RELEASE_TEMPLATE_LIST: "app.image.registry=${SAMO_DOCKER_RELEASE_REGISTRY},app.image.tag={{ .Release }},app.image.repository=1000kit/{{ .Name }}"
      SAMO_HELM_CHART_RELEASE_TEMPLATE_LIST: 'version={{ .Release }},appVersion={{ .Release }},name={{ .Name }}'
    steps:
    - uses: lorislab/install-samo-action@v1
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.SAMO_DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}        
    - uses: actions/download-artifact@v3
      with:
        name: package
        path: ${{ inputs.packageDir }}      
    - name: helm build
      run: samo project helm build -v debug
    - name: helm push
      run: samo project helm push -v debug 
