name: Create new build

on:
  workflow_call:

jobs:
  build:
    name: create new build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}
          ref: ${{ github.head_ref }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--allow-empty'
          commit_message: 'chore(ci): create new build'