name: dependency-review

on:
  workflow_call:
    inputs:
      failOnSeverity:
        description: 'Defines the threshold for the level of severity. Values low, moderate, high, critical.'
        default: 'low'
        required: false
        type: string
        
jobs:
  dependency-review:
    name: dependency review
    runs-on: ubuntu-latest
    permissions:
      contents: read    
    steps:
      - uses: actions/checkout@v5
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: ${{ inputs.failOnSeverity }}
