name: trivy

on:
  workflow_call:
    inputs: 
      native:
        description: 'Build native image'
        default: false
        required: false
        type: boolean
      artifact:
        description: 'Name of the artifact for the build'
        default: 'quarkus-version'
        required: false
        type: string   
      artifactPath:
        description: 'Artifact path'
        default: 'quarkus-version.txt'
        required: false
        type: string
jobs:
  trivy:
    name: docker trivy scan
    # runs-on: [ self-hosted, aws ]
    runs-on: ubuntu-latest
    env:
      TRIVY_DEPENDENCY_TREE: 'true'
    steps:
      - uses: dawidd6/action-download-artifact@v20
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ inputs.artifact }}
          if_no_artifact_found: ignore
      - uses: juliangruber/read-file-action@v1
        if: ${{ hashFiles( inputs.artifactPath ) != '' }}
        id: version_tag
        with:
          path: ./${{ inputs.artifactPath }}
      - name: Get the build version
        if: ${{ hashFiles( inputs.artifactPath ) != '' }}
        run: |
          echo "APPLICATION_VERSION=${{ steps.version_tag.outputs.content }}" >> $GITHUB_ENV
      - name: Run Trivy vulnerability scanner for app version
        if: ${{ hashFiles( inputs.artifactPath ) != '' }}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.APPLICATION_VERSION }}'
          severity: 'HIGH,CRITICAL'
          format: table
      - name: Run Trivy vulnerability scanner for latest
        if: ${{ hashFiles( inputs.artifactPath ) == '' }}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:main'
          severity: 'HIGH,CRITICAL'
          format: table
  trivy-native:
    if: ${{ inputs.native }}
    name: docker trivy scan native
    # runs-on: [ self-hosted, aws ]
    runs-on: ubuntu-latest
    env:
      TRIVY_DEPENDENCY_TREE: 'true'
    steps:
      - uses: dawidd6/action-download-artifact@v20
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ inputs.artifact }}
          if_no_artifact_found: ignore
      - uses: juliangruber/read-file-action@v1
        if: ${{ hashFiles( inputs.artifactPath ) != '' }}
        id: version_tag
        with:
          path: ./${{ inputs.artifactPath }}
      - name: Get the build version
        if: ${{ hashFiles( inputs.artifactPath ) != '' }}
        run: |
          echo "APPLICATION_VERSION=${{ steps.version_tag.outputs.content }}" >> $GITHUB_ENV
      - name: Run Trivy vulnerability scanner for app version
        if: ${{ hashFiles( inputs.artifactPath ) != '' }}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.APPLICATION_VERSION }}-native'
          severity: 'HIGH,CRITICAL'
          format: table
      - name: Run Trivy vulnerability scanner for latest
        if: ${{ hashFiles( inputs.artifactPath ) == '' }}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:main-native'
          severity: 'HIGH,CRITICAL'
          format: table
