name: trivy

on:
  workflow_call:
    inputs: 
      artifact:
        description: 'Name of the artifact for the build'
        default: 'quarkus-version'
        required: false
        type: string   
      artifactPath:
        description: 'Artifact path'
        default: 'quarkus-version.txt'
        required: false
        type: string
jobs:
  trivy:
    name: docker trivy scan
    # runs-on: [ self-hosted, aws ]
    runs-on: ubuntu-latest
    env:
      TRIVY_DEPENDENCY_TREE: 'true'
    steps:
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check_coverage_artifact
        with:
          name: '${{ inputs.artifact }}'
      - uses: dawidd6/action-download-artifact@v3
        if: ${{ steps.check_coverage_artifact.outputs.exists }}
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: ${{ inputs.artifact }}
      - uses: juliangruber/read-file-action@v1
        if: ${{ steps.check_coverage_artifact.outputs.exists }}
        id: version_tag
        with:
          path: ./${{ inputs.artifactPath }}
      - name: Run Trivy vulnerability scanner
        if: ${{ steps.check_coverage_artifact.outputs.exists }}
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.version_tag.outputs.content }}'
          severity: 'HIGH,CRITICAL'
          format: table
