name: documentation
on:
  workflow_call:
    docs:
      tags:
        description: 'Documentation repository'
        default: 'docs'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_PAT }}
          repository: onecx/${{ inputs.docs }}
          event-type: dispatch-build-website