name: helm-deploy

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        description: 'Helm copy and filter source directory'
        required: true
        type: string  
      EKS_CLUSTER_NAME:
        description: 'Helm copy and filter source directory'
        required: true
        type: string          
      HELM_CHART_URL:
        description: 'Package directory'
        required: true
        type: string
      HELM_REPO_NAME:
        description: 'Package directory'
        required: false
        type: string  
      HELM_REPO_URL:
        description: 'Package directory'
        required: false
        type: string     
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  docker:
    name: build and push
    runs-on: [ self-hosted, ecs ]
    env:
      HELM_CHART_URL: ${{ inputs.HELM_CHART_URL }}
      HELM_REPO_NAME: ${{ inputs.HELM_REPO_NAME }}
      HELM_REPO_URL: ${{ inputs.HELM_REPO_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
      EKS_CLUSTER_NAME: ${{ inputs.EKS_CLUSTER_NAME }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: get kubeconfig
      run: aws eks update-kubeconfig --region ${AWS_DEFAULT_REGION} --name ${EKS_CLUSTER_NAME}
    - name: add helm repo
      run: helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
    - name: helm install
      run: helm install test .
