name: Update helm chart dependencies

on:
  workflow_call:
    inputs:
      helmSourceDir:
        description: 'Helm source directory path'
        default: 'helm'
        required: false
        type: string

jobs:
  build:
    name: helm chart update dependency
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Event
        run: echo ${{ github.event.client_payload }}
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}
          ref: ${{ github.head_ref }}
      - name: Update helm chart
        run:
          samo project helm deps-update --helm-absolute-dir --helm-dir ${{ inputs.helmSourceDir }} --helm-deps-name ${{ github.event.client_payload.repo }} --helm-deps-version ${{ github.event.client_payload.version }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(deps): update ${{ github.event.client_payload.repo }} to version ${{ github.event.client_payload.version }}'
